### ISSUE TITLE
Path parameter is incorrect.

### ISSUE THREAD

**Issue by zrivkis** [nmantani/PS-MOTW#2]
Documentation refers to "Path" as the expected parameter, while code has "Paths".

`[parameter(ValueFromRemainingArguments=$true)]$Paths`

![image](https://github.com/nmantani/PS-MOTW/assets/66017948/0a041a9b-2692-44b9-a166-0d32aba93d2b)

**Comment by nmantani** [comment]
Thank you for spotting! I have fixed it.
